### ISSUE TITLE
Setting 중 발생한 에러: "bind source path does not exist"

### ISSUE THREAD

**Issue by PullStackCoder** [mmtechcommunity/zomm-backend-core#13]
Docker 부터 Gradle 까지 설치하고(버전에 맞게), git clone 한 후, docker-compose up 명령을 실행하면 다음과 같은 에러가 발생합니다:

$ docker-compose up
[+] Running 33/33
 ⠿ prometheus Pulled                                                                                                                                             15.7s
   ⠿ aa2a8d90b84c Pull complete                                                                                                                          2.0s
   ⠿ b45d31ee2d7f Pull complete                                                                                                                          3.6s
   ⠿ da9de9139824 Pull complete                                                                                                                          6.4s
   ⠿ d04e751b88d5 Pull complete                                                                                                                          8.8s

... (생략) ...

  => => extracting sha256:a924923085ccc86e36f9275727916040cd456bf7e1c30e347d143b5c3e22cd03                                                                6.0s
 => => extracting sha256:1ff28fbb815da336245bc0555e56c33a4986001ae0f9ebadf70a4df1623a83cd                                                                3.7s
 => [2/4] COPY . /app                                                                                                                                            0.3s
 => [3/4] WORKDIR /app                                                                                                                                       0.0s
 => [4/4] RUN gradle clean build -x test                                                                                                               136.9s
 => exporting to image                                                                                                                                           1.6s
 => => exporting layers                                                                                                                                          1.6s
 => => writing image sha256:1346b8f50db2f9465fb06a79454dd51f2f2f11ed9a61ece05443a576a9200d9b                                                             0.0s 
 => => naming to docker.io/library/zomm-backend-core_core-service                                                                                        0.0s 
                                                                                                                                                              
Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them                                                          
[+] Running 4/5
 ⠿ Network zomm-backend-core_zomm  Created                                                                                                 0.5s
 ⠿ Container node-exporter         Created                                                                                                               0.2s
 ⠿ Container db                    Created                                                                                                                       0.2s
 ⠿ Container core-service          Created                                                                                                                 1.1s
 ⠙ Container prometheus            Creating                                                                                                               0.2s
Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /Users/TJ/.prometheus

**Comment by rostradamus** [comment]
docker-compose 사용시 volume이 bind type으로 mount 되는것 같습니다... (https://stackoverflow.com/questions/48971065/getting-invalid-mount-config-for-type-bind-bind-source-path-does-not-exist-in)
확인 후 링크된 PR로 bug fix commit 하도록하겠습니다 :)

**Comment by PullStackCoder** [comment]
알려주신대로 해서 해결 되었습니다
